### PR TITLE
Allow users to specify character persona

### PR DESCRIPTION
**Pull request by ghost**
* Users can download any character json files for UIs like Tavern and use it with `personaFile` config. Example - https://www.chub.ai/characters/thyholyjebus77/charles-darwin
* Works best with pygmalion-7b or 13b models. They are llama based so work with existing llama.cpp server. Using the following right now - https://huggingface.co/notstoic/pygmalion-13b-ggml/blob/main/pygmalion-13b-ggml-q4_1.bin
* Need to keep the server context to 2048 tho cause persona's and example dialogues can be long.
* Minor - make server url configurable

### CODE REVIEW

**Comment by choombaa** [comment]
Using 'Alice:' as a stop token is a good call

**Comment by ghost** [comment]
> Using 'Alice:' as a stop token is a good call

Yeah otherwise it sometimes generates dialogues for You (the user) as well.

**Review by yacineMTB — APPROVED** [review]
ship it

**Comment by jmanhype** [comment]
Only issue is you need to remove the stream: true,
        stop: stopTokens, leave just stream true because when you dont it cuts off the ai response. So if i ask for a recipe it only says one line and then waits for me to say something. When you tske it off it actually tells you entire recipe. It can tell your entire storys if you take that off

**Comment by ghost** [comment]
@jmanhype Aha, yeah I am thinking of a better way using logit_bias so that don't have to use stop tokens at all. Streaming is necessary so that the delay b/w when the user starts receiving response is reduced.

**Comment by jmanhype** [comment]
Alright so with this and the other ones remove artifacts etc. And with me taking the stop off im getting good results. How to make it better make it so it mutes itself after i press R. Basically give me a mute button or mute trigger ive had really long conversations when i manually mute in between responses

**Pull request merged**
